import Foundation

public struct LampAgentMCPConfiguration: Equatable, Sendable {
    public let helperExecutableURL: URL
    public let libraryRootURL: URL
    public let bundledModulesArchiveURL: URL?
    public let policyURL: URL

    public init(
        helperExecutableURL: URL,
        libraryRootURL: URL,
        bundledModulesArchiveURL: URL? = nil,
        policyURL: URL
    ) {
        self.helperExecutableURL = helperExecutableURL
        self.libraryRootURL = libraryRootURL
        self.bundledModulesArchiveURL = bundledModulesArchiveURL
        self.policyURL = policyURL
    }

    public var arguments: [String] {
        var result = ["--library-root", libraryRootURL.path]
        if let bundledModulesArchiveURL {
            result += ["--bundled-modules-archive", bundledModulesArchiveURL.path]
        }
        result += ["--policy", policyURL.path]
        return result
    }

    public func writeProviderConfigurations(to workspace: URL) throws {
        let fileManager = FileManager.default
        let codexDirectory = workspace.appendingPathComponent(".codex", isDirectory: true)
        try fileManager.createDirectory(at: codexDirectory, withIntermediateDirectories: true)
        try codexTOML.write(
            to: codexDirectory.appendingPathComponent("config.toml"),
            atomically: true,
            encoding: .utf8
        )
        try claudeJSON.write(
            to: workspace.appendingPathComponent(".mcp.json"),
            atomically: true,
            encoding: .utf8
        )
        try openCodeJSON.write(
            to: workspace.appendingPathComponent("opencode.json"),
            atomically: true,
            encoding: .utf8
        )
    }

    public var codexTOML: String {
        let encodedArguments = arguments.map(Self.quoted).joined(separator: ", ")
        return """
        # Generated by Lamp Bible. Recreated when this devotional workspace opens.
        [mcp_servers.lamp]
        command = \(Self.quoted(helperExecutableURL.path))
        args = [\(encodedArguments)]
        required = true
        startup_timeout_sec = 15
        tool_timeout_sec = 60
        default_tools_approval_mode = "auto"
        """ + "\n"
    }

    public var claudeJSON: String {
        Self.prettyJSON([
            "mcpServers": [
                "lamp": [
                    "type": "stdio",
                    "command": helperExecutableURL.path,
                    "args": arguments,
                ] as [String: Any],
            ],
        ])
    }

    public var openCodeJSON: String {
        Self.prettyJSON([
            "$schema": "https://opencode.ai/config.json",
            "mcp": [
                "servers": [
                    "lamp": [
                        "type": "local",
                        "command": [helperExecutableURL.path] + arguments,
                        "codemode": false,
                    ] as [String: Any],
                ],
            ],
        ])
    }

    private static func quoted(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        return "\"\(escaped)\""
    }

    private static func prettyJSON(_ object: [String: Any]) -> String {
        guard let data = try? JSONSerialization.data(
            withJSONObject: object,
            options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        ) else { return "{}\n" }
        return String(decoding: data, as: UTF8.self) + "\n"
    }
}
